---
- name: Obtener tiempo de encendido del PC con Ubuntu
  hosts: all   # Cambia esto por tu grupo de hosts o IP de la máquina
  gather_facts: yes         # Asegura que se recojan todos los hechos posibles

  tasks:
    - name: Ejecutar el comando 'uptime' para obtener el tiempo de encendido
      command: uptime -s
      register: uptime_output
      changed_when: false  # No marcamos esta tarea como cambiada, ya que solo estamos leyendo datos

    - name: Mostrar tiempo de encendido
      debug:
        msg: "El sistema se encendió por última vez el: {{ uptime_output.stdout }}"
